### ISSUE TITLE
class method binding

### ISSUE THREAD

**Issue by idoros** [zenparsing/es-function-bind#16]
it would be nice to have the same ability in classes, which would give automatic binding to class instance for selected methods:
```javascript
class Foo{
 method(){}
 ::boundToInstanceMethod(){ 
  // this is always referenced to the instance  
 }
}
```

**Comment by nathggns** [comment]
Great suggestions!! So many times I have to do () => this.foo() instead of this.foo.

**Comment by zenparsing** [comment]
Thanks @idoros .  Developers commonly want methods of a class autobound.  Unfortunately, this proposal doesn't offer the appropriate semantics to support this, since at class definition time there's no instance to bind the method to.

Is there a particular use case that the unary bind operator doesn't address?

```js
class Foo {
    method() {}
}

let f = new Foo();
let boundMethod = ::f.method;
```

**Comment by nathggns** [comment]
Could you not do a syntactical transform like the following?

```js
class Foo {
    ::someMethod() {
        // this will always be instance of Foo
    }
}
```

```js
var Foo = (function() {
    var Foo = function() {
        this.someMethod = this.someMethod.bind(this);
    };

    Foo.prototype.someMethod = function() {
        // this will always be instance of Foo
    };

    return Foo;
})();

**Comment by idoros** [comment]
@nathggns, +1 
That was what I was thinking...

**Comment by zenparsing** [comment]
Perhaps this could be added in the future, but closing for now.
